### PR TITLE
[chore] Add clock to utils

### PR DESCRIPTION
**Pull request by cedric-cordenier**
Moving this from core into common.

Companion PR: https://github.com/smartcontractkit/chainlink/pull/12027

### CODE REVIEW

**Review by DeividasK — APPROVED** [review]
Could do with a PR comment to explain why this is moved (I assume one of the capabilities will need it?)

**Comment by jmank88** [comment]
Is there another package that would make more sense? We've been trying to dissolve `package utils` since it is an anti-pattern

**Comment by cedric-cordenier** [comment]
@jmank88 I could move it to a faketime package in ./pkg? Or into utils/tests?

**Comment by bolekk** [comment]
pkg/clock ?

**Pull request merged**
