### PR TITLE
Allow chain reader tests to run outside the testing environment to enable testing real chains as part of an application

### PR DESCRIPTION
**Pull request by nolag**

### CODE REVIEW

**Review by EasterTheBunny — APPROVED** [review]
LGTM

**Comment by jmank88** [comment]
Why do we have to avoid the standard testing framework in order to execute against real chains? These seem like separate concerns.

**Comment by nolag** [comment]
> Why do we have to avoid the standard testing framework in order to execute against real chains? These seem like separate concerns.

The tool it's being used with isn't running as a test.

**Review by jmank88 — DISMISSED** [review]

**Review by jmank88 — APPROVED** [review]

**Review by EasterTheBunny — APPROVED** [review]
LGTM

**Pull request merged**
