### PR TITLE
[KS-44] Transparently wrap values

### PR DESCRIPTION
**Pull request by cedric-cordenier**

### CODE REVIEW

**Review by bolekk — COMMENTED** [review]
lgtm

**Comment by bolekk** [comment]
Still planning to merge this?

**Comment by bolekk** [comment]
ping - I think this could be useful

**Comment by cedric-cordenier** [comment]
Yes, definitely planning on merging this as soon as I get back :) This took
the back seat while I was trying to wrap up the OCR3 capability.

**Review by jmank88 — APPROVED** [review]

**Pull request merged**
