### PR TITLE
Chain writer mocks

### PR DESCRIPTION
**Pull request by silaslenihan**

### CODE REVIEW

**Review by jmank88 — CHANGES_REQUESTED** [review]
Why generate unused mocks? If importers want these, they can generate them on their own. That keeps their mockery version aligned internally as well.

**Comment by silaslenihan** [comment]
> Why generate unused mocks? If importers want these, they can generate them on their own. That keeps their mockery version aligned internally as well.

@jmank88 Sorry I'm not sure what you mean, can these mocks be generated post-import in the main `chainlink` repo?

**Comment by jmank88** [comment]
> > Why generate unused mocks? If importers want these, they can generate them on their own. That keeps their mockery version aligned internally as well.
> 
> @jmank88 Sorry I'm not sure what you mean, can these mocks be generated post-import in the main `chainlink` repo?   

AFAIK Yes, and I think that should be preferred

**Comment by silaslenihan** [comment]
Closed in favor of generating mocks post-import

**Pull request closed without merging**
